name: java-jre-ondra
version: "8u131-b11-2ubuntu1.17.04.3"
version-script: |
   echo $(find parts/jre/ubuntu/download/ -name "openjdk-8-jre_*_amd64.deb" | awk -F  "/" '{print $5}' | awk -F  "_" '{print $2}')
summary: java 8 runtime snap
description: |
 Java 8 run time snap, this snap is intented to be used by other snap_fileset
 using content interface

confinement: strict
grade: stable

slots:
  jre:
    interface: content
    read:
      - $SNAP

environment:
  JAVA_HOME: ${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}
  PATH: ${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}/bin:$PATH

apps:
    info:
        command: print-info

parts:
    # java run time
    jre:
        plugin: nil
        stage-packages:
          - openjdk-8-jre
    info:
        plugin: dump
        source: snap
