name: java-jre-ondra
version: "8_8u121-b13"
summary: java 8 runtime snap
description: |
 Java 8 run time snap, this snap is intented to be used by other snap_fileset
 using content interface
 arm64 runtime is coming fropm openjdk-8-jre

confinement: strict
grade: stable

slots:
  jre:
    interface: content
    read:
      - $SNAP

apps:
    info:
        command: print-info

parts:
    # java run time
    jre:
        plugin: zulu-jre
        # zulu supported architectures(armhf, amd64) are already handled by plugin itself
        # define here overide for pluging's defaults, or to add additional architectures
        # architectures: armhf, armel, arm64, amd64, i386
        # example overide:
        # zulu:
        #     amd64: https://www.azul.com/downloads/zulu/zdk-8-ga-linux_x64.tar.gz

    info:
        plugin: dump
        source: snap
        stage:
          - -plugins
        prime:
          - -plugins
